version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9112:9112"
    env_file:
      - .env.local
    volumes:
      - .:/app
      - ./uploads:/app/public/uploads
    command: npm run dev
